version: "3"
services:
  bootnode:
    build: .
    container_name: bootnode
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "3000"]
      interval: 2s
      retries: 3
      start_period: 5s
    command:
      - "-grpc.addr=:3000"
      - "-crypto.seed=97d3a71712a442f6345e16df34ecec93c3f6666dc84cee739c2e95a878ea99e1"
    expose:
      - "3000"

  validator:
    build: .
    container_name: validator
    depends_on:
      bootnode:
        condition: service_healthy
    command:
      - "-grpc.addr=:4000"
      - "-grpc.bootnodes=bootnode:3000"
      - "-crypto.seed=97d3a71712a442f6345e16df34ecec93c3f6666dc84cee739c2e95a878ea99e2"
      - "-validator=true"
    expose:
      - "4000"